CREATE TABLE `committee_members` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`name_en` text NOT NULL,
	`name_kn` text DEFAULT '' NOT NULL,
	`role_en` text DEFAULT '' NOT NULL,
	`role_kn` text DEFAULT '' NOT NULL,
	`photo` text DEFAULT '' NOT NULL,
	`phone` text DEFAULT '' NOT NULL,
	`bio_en` text DEFAULT '' NOT NULL,
	`bio_kn` text DEFAULT '' NOT NULL,
	`published` integer DEFAULT true NOT NULL,
	`sort_order` integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE `landmarks` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`project_id` integer NOT NULL,
	`name_en` text NOT NULL,
	`name_kn` text DEFAULT '' NOT NULL,
	`category` text DEFAULT 'other' NOT NULL,
	`lat` real NOT NULL,
	`lng` real NOT NULL,
	`drive_minutes` integer,
	`sort_order` integer DEFAULT 0 NOT NULL,
	FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `leads` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`name` text NOT NULL,
	`phone` text NOT NULL,
	`email` text DEFAULT '' NOT NULL,
	`project_id` integer,
	`site_id` integer,
	`purpose` text DEFAULT 'self_use' NOT NULL,
	`budget` text DEFAULT '' NOT NULL,
	`timeline` text DEFAULT '' NOT NULL,
	`message` text DEFAULT '' NOT NULL,
	`locale` text DEFAULT 'en' NOT NULL,
	`source` text DEFAULT '' NOT NULL,
	`status` text DEFAULT 'new' NOT NULL,
	`notes` text DEFAULT '' NOT NULL,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`site_id`) REFERENCES `sites`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE TABLE `projects` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`slug` text NOT NULL,
	`name_en` text NOT NULL,
	`name_kn` text DEFAULT '' NOT NULL,
	`tagline_en` text DEFAULT '' NOT NULL,
	`tagline_kn` text DEFAULT '' NOT NULL,
	`description_en` text DEFAULT '' NOT NULL,
	`description_kn` text DEFAULT '' NOT NULL,
	`location_en` text DEFAULT '' NOT NULL,
	`location_kn` text DEFAULT '' NOT NULL,
	`lat` real,
	`lng` real,
	`total_area_acres` real,
	`total_sites` integer,
	`status` text DEFAULT 'ongoing' NOT NULL,
	`approvals` text DEFAULT '[]' NOT NULL,
	`amenities` text DEFAULT '[]' NOT NULL,
	`cover_image` text DEFAULT '' NOT NULL,
	`gallery` text DEFAULT '[]' NOT NULL,
	`layout_plan_image` text DEFAULT '' NOT NULL,
	`brochure_url` text DEFAULT '' NOT NULL,
	`video_url` text DEFAULT '' NOT NULL,
	`price_from` integer,
	`price_per_sqft` integer,
	`featured` integer DEFAULT false NOT NULL,
	`published` integer DEFAULT true NOT NULL,
	`sort_order` integer DEFAULT 0 NOT NULL,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `projects_slug_unique` ON `projects` (`slug`);--> statement-breakpoint
CREATE TABLE `settings` (
	`id` integer PRIMARY KEY NOT NULL,
	`society_name_en` text DEFAULT 'Mathrushree Housing Co-operative Society Limited' NOT NULL,
	`society_name_kn` text DEFAULT 'ಮಾತೃಶ್ರೀ ಹೌಸಿಂಗ್ ಕೋ-ಆಪರೇಟಿವ್ ಸೊಸೈಟಿ ಲಿಮಿಟೆಡ್' NOT NULL,
	`tagline_en` text DEFAULT '' NOT NULL,
	`tagline_kn` text DEFAULT '' NOT NULL,
	`phone_primary` text DEFAULT '' NOT NULL,
	`phone_secondary` text DEFAULT '' NOT NULL,
	`whatsapp` text DEFAULT '' NOT NULL,
	`email` text DEFAULT '' NOT NULL,
	`address_en` text DEFAULT '' NOT NULL,
	`address_kn` text DEFAULT '' NOT NULL,
	`reg_number` text DEFAULT '' NOT NULL,
	`established_year` integer,
	`about_en` text DEFAULT '' NOT NULL,
	`about_kn` text DEFAULT '' NOT NULL,
	`hero_image` text DEFAULT '' NOT NULL,
	`hero_title_en` text DEFAULT '' NOT NULL,
	`hero_title_kn` text DEFAULT '' NOT NULL,
	`hero_subtitle_en` text DEFAULT '' NOT NULL,
	`hero_subtitle_kn` text DEFAULT '' NOT NULL,
	`office_lat` real,
	`office_lng` real,
	`working_hours_en` text DEFAULT '' NOT NULL,
	`working_hours_kn` text DEFAULT '' NOT NULL,
	`stat_members` integer DEFAULT 0 NOT NULL,
	`stat_sites_allotted` integer DEFAULT 0 NOT NULL,
	`stat_projects_completed` integer DEFAULT 0 NOT NULL,
	`facebook_url` text DEFAULT '' NOT NULL,
	`instagram_url` text DEFAULT '' NOT NULL,
	`youtube_url` text DEFAULT '' NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL
);
--> statement-breakpoint
CREATE TABLE `sites` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`project_id` integer NOT NULL,
	`site_number` text NOT NULL,
	`dimension` text DEFAULT '' NOT NULL,
	`width_ft` real,
	`depth_ft` real,
	`area_sqft` real,
	`facing` text,
	`road_width_ft` real,
	`corner` integer DEFAULT false NOT NULL,
	`status` text DEFAULT 'available' NOT NULL,
	`price` integer,
	`price_per_sqft` integer,
	`lat` real,
	`lng` real,
	`description_en` text DEFAULT '' NOT NULL,
	`description_kn` text DEFAULT '' NOT NULL,
	`images` text DEFAULT '[]' NOT NULL,
	`features` text DEFAULT '[]' NOT NULL,
	`sort_order` integer DEFAULT 0 NOT NULL,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `testimonials` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`name_en` text NOT NULL,
	`name_kn` text DEFAULT '' NOT NULL,
	`location_en` text DEFAULT '' NOT NULL,
	`location_kn` text DEFAULT '' NOT NULL,
	`quote_en` text DEFAULT '' NOT NULL,
	`quote_kn` text DEFAULT '' NOT NULL,
	`project_id` integer,
	`photo` text DEFAULT '' NOT NULL,
	`published` integer DEFAULT true NOT NULL,
	`sort_order` integer DEFAULT 0 NOT NULL,
	FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE set null
);
